name: Release

on:
  workflow_dispatch: # Disabled automatic releases - only manual trigger

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npm run install-browsers

      - name: Build project
        run: npm run build

      - name: Start MCP server
        run: |
          node dist/index.js &
          SERVER_PID=$!
          echo "SERVER_PID=${SERVER_PID}" >> $GITHUB_ENV
          # Wait for server to start up
          sleep 3

      - name: Run tests
        run: npm test

      - name: Stop MCP server
        if: always()
        run: |
          if [ ! -z "$SERVER_PID" ]; then
            kill $SERVER_PID || true
          fi

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  github-release:
    runs-on: ubuntu-latest
    needs: publish

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        id: changelog
        run: |
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD~1 2>/dev/null || echo "")
          if [ -n "$PREVIOUS_TAG" ]; then
            CHANGES=$(git log --pretty=format:"- %s" $PREVIOUS_TAG..HEAD)
          else
            CHANGES=$(git log --pretty=format:"- %s" --since="2023-01-01")
          fi
          echo "changes<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.release_tag }}
          release_name: Release ${{ inputs.release_tag }}
          body: |
            ## Changes
            ${{ steps.changelog.outputs.changes }}
          draft: false
          prerelease: false
